name: Deploy

on:
  push:
    paths:
      - 'pure-blog-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pure-blog-backend" #Must be unique in Heroku
          heroku_email: "jotyy318@gmail.com"
          appdir: "pure-blog-backend"
